### ISSUE TITLE
go land_detail not working

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/PyFerret#96]
**TMAP ERR: non-existent or not on line
             Searched $FER_DESCR and $FER_DATA for geo_borders_intermed(.nc ,.cdf,.des)

This works in normal ferret but not pyferret

**Comment by haze1986** [comment]
Thanks for this, do you mind sharing which version do I need to be on? v7.5 is fine?

I have problems installing v7.6 on my ubuntu system as I cant run python 3.6 on it

**Comment by ACManke** [comment]
Hello,

Update your installation of the datasets. The current  release is found at

https://github.com/NOAA-PMEL/FerretDatasets/releases/tag/v7.6

This should solve your problem for any PyFerret version.

Ansley

**Comment by haze1986** [comment]
Hmm still did not work for me. I am using the latest release of the datasets. It works for ferret but not pyferret

**Comment by ACManke** [comment]
The datasets installation and handling is the same whether you are using Ferret or PyFerret.  It seems that you have different datasets directories for the two programs, so that your PyFerret installation is not using the same data directory as your Ferret installation.  From a Ferret session, see where the file used by "go land_detail" is

yes? use geo_borders_intermed
yes? show data

This will list the file with its path.

Now, run PyFerret, and see where datasets are being found.  The dataset that "go land" uses, is geo_borders.cdf:

yes? use geo_borders 

Compare the paths.  You could either copy geo_borders_intermed.nc  from the location where Ferret finds it, to the location where PyFerret finds geo_borders.cdf, or you could change your PyFerret environment so that the environment variable FER_DIR includes the same directory that Ferret uses.

**Comment by haze1986** [comment]
1 /home/haze/fer_dsets/FerretDatasets-7.6/data/geo_borders_intermed.nc

2 /home/haze/fer_dsets/FerretDatasets-7.6/data/geo_borders.cdf

They are the same.
